export enum EWeatherMetaDataActionType {
  GET_WEATHER_INFO_BY_LOCATION = "GET_WEATHER_INFO_BY_LOCATION",
  SET_SUCCESS_STATUS = "SET_SUCCESS_STATUS",
  SET_ONPROGRESS_STATUS = "SET_ONPROGRESS_STATUS",
  SET_FAILURE_STATUS = "SET_FAILURE_STATUS"
}

export enum EWeatherSagaWatcherType {
  GET_WEATHER_INFO_BY_LOCATION_WATCHER = "GET_WEATHER_INFO_BY_LOCATION_WATCHER"
}